esphome:
  name: esphome-web-2d28a0
  friendly_name: ESPHome Macropad
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# 16 physical buttons → each calls a HA script (script.macro_1 ... script.macro_16)
binary_sensor:
  # Key 1 → GPIO15
  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 1"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_1

  # Key 2 → GPIO22 (moved off GPIO2 to avoid strap/LED quirks)
  - platform: gpio
    pin:
      number: GPIO22
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 2"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_2

  # Key 3 → GPIO4
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 3"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_3

  # Key 4 → GPIO16
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 4"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_4

  # Key 5 → GPIO5
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 5"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_5

  # Key 6 → GPIO18
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 6"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_6

  # Key 7 → GPIO19
  - platform: gpio
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 7"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_7

  # Key 8 → GPIO21
  - platform: gpio
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 8"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_8

  # Key 9 → GPIO13
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 9"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_9

  # Key 10 → GPIO12
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 10"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_10

  # Key 11 → GPIO14
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 11"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_11

  # Key 12 → GPIO27
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 12"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_12

  # Key 13 → GPIO25
  - platform: gpio
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 13"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_13

  # Key 14 → GPIO33
  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 14"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_14

  # Key 15 → GPIO32
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 15"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_15

  # Key 16 → GPIO23
  - platform: gpio
    pin:
      number: GPIO23
      mode: INPUT_PULLUP
      inverted: true
    name: "Macro Key 16"
    on_press:
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.macro_16
